config/routes.rb
Rails.application.routes.draw do
  resources :oeuvres
  resources :images
  resources :artists
  resources :colors
  root to: "colors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
	has_many :oeuvres
	def to_s
		"#{color}"
	end 
end

app/models/oeuvre.rb
class Oeuvre < ApplicationRecord
  belongs_to :color
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:image, :color, :history, :symb)
    end
end

app/controllers/oeuvres_controller.rb
class OeuvresController < ApplicationController
  before_action :set_oeuvre, only: [:show, :edit, :update, :destroy]

  # GET /oeuvres
  # GET /oeuvres.json
  def index
    @oeuvres = Oeuvre.all
  end

  # GET /oeuvres/1
  # GET /oeuvres/1.json
  def show
  end

  # GET /oeuvres/new
  def new
    @oeuvre = Oeuvre.new
  end

  # GET /oeuvres/1/edit
  def edit
  end

  # POST /oeuvres
  # POST /oeuvres.json
  def create
    @oeuvre = Oeuvre.new(oeuvre_params)

    respond_to do |format|
      if @oeuvre.save
        format.html { redirect_to @oeuvre, notice: 'Oeuvre was successfully created.' }
        format.json { render :show, status: :created, location: @oeuvre }
      else
        format.html { render :new }
        format.json { render json: @oeuvre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oeuvres/1
  # PATCH/PUT /oeuvres/1.json
  def update
    respond_to do |format|
      if @oeuvre.update(oeuvre_params)
        format.html { redirect_to @oeuvre, notice: 'Oeuvre was successfully updated.' }
        format.json { render :show, status: :ok, location: @oeuvre }
      else
        format.html { render :edit }
        format.json { render json: @oeuvre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oeuvres/1
  # DELETE /oeuvres/1.json
  def destroy
    @oeuvre.destroy
    respond_to do |format|
      format.html { redirect_to oeuvres_url, notice: 'Oeuvre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oeuvre
      @oeuvre = Oeuvre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oeuvre_params
      params.require(:oeuvre).permit(:url, :color_id, :title, :artist, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/oeuvres_helper.rb
module OeuvresHelper
end

app/views/colors/_form.html.erb
<%= form_with(model: color, local: true) do |form| %>
  <% if color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="field">
    <%= form.label :symb %>
    <%= form.text_area :symb %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing Color</h1>

<%= render 'form', color: @color %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

app/views/colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colors Museum</h1>
<br>
<br>
<br>



    <% @colors.each do |color| %>
      <%= link_to color do %>
        <%= image_tag color.image, class: "rounded-circle", style: "max-width : 15%; border: 2px solid #DBDCDE;"  %>
      <% end %>
    <% end %>

<br>

app/views/colors/new.html.erb
<h1>New Color</h1>

<%= render 'form', color: @color %>

<%= link_to 'Back', colors_path %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @color.image, class: "rounded-circle", style: "width: 20%" %>
</p>

<br>
<strong style="font-size: 60PX"><%= @color.color %></strong>


<p>
	<%= link_to 'Back', colors_path %>
<br>

<table style="width:100%" class="table">

<tr>
  <th><strong style="font-size: 30PX">Historique</strong></th>
  <th><strong style="font-size: 30PX">Symbolique</strong></th>
</tr>

<tr>
	 <td style="max-width: 400px"><%= simple_format @color.history %></td>
	 <td style="max-width: 400px"><%= simple_format @color.symb %></td>

</tr>

  </table>

  	 <div>
	    <% @color.oeuvres.each do |oeuvre| %>
			<div>
			<%= image_tag oeuvre.url, style: "width: 700px" %>
			</div>
			<div>
			<%= oeuvre.title %>
			</div>
			<div>
			<%= oeuvre.artist %>
			</div>
			<div>
			<%= oeuvre.date %>
			</div>
			<br>
		<% end %>
	</div>

</p>


<%= link_to 'Edit', edit_color_path(@color), style: "color: white" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">

<html>
  <head>
    <title>Colors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
          <%= yield %>
    </div>

  </body>

</html>

app/views/oeuvres/_form.html.erb
<%= form_with(model: oeuvre, local: true) do |form| %>
  <% if oeuvre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oeuvre.errors.count, "error") %> prohibited this oeuvre from being saved:</h2>

      <ul>
      <% oeuvre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.select :color_id, Color.all.map {|color| [color.color, color.id] } %>
 
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oeuvres/edit.html.erb
<h1>Editing Oeuvre</h1>

<%= render 'form', oeuvre: @oeuvre %>

<%= link_to 'Show', @oeuvre %> |
<%= link_to 'Back', oeuvres_path %>

app/views/oeuvres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oeuvres</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Color</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oeuvres.each do |oeuvre| %>
      <tr>
        <td><%= oeuvre.url %></td>
        <td><%= oeuvre.color %></td>
        <td><%= oeuvre.title %></td>
        <td><%= oeuvre.artist %></td>
        <td><%= oeuvre.date %></td>
        <td><%= link_to 'Show', oeuvre %></td>
        <td><%= link_to 'Edit', edit_oeuvre_path(oeuvre) %></td>
        <td><%= link_to 'Destroy', oeuvre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oeuvre', new_oeuvre_path %>

app/views/oeuvres/new.html.erb
<h1>New Oeuvre</h1>

<%= render 'form', oeuvre: @oeuvre %>

<%= link_to 'Back', oeuvres_path %>

app/views/oeuvres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= image_tag @oeuvre.url %>
</p>

<p>
  <strong>Color:</strong>
  <%= link_to @oeuvre.color, @oeuvre.color %>
</p>



<p>
  <strong>Artist:</strong>
  <%= @oeuvre.artist %>
</p>

<p>
  <strong>Date:</strong>
  <%= @oeuvre.date %>
</p>

<%= link_to 'Edit', edit_oeuvre_path(@oeuvre) %> |
<%= link_to 'Back', oeuvres_path %>